[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.4"
scraper = "0.19.0"
select = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.10"
futures = "0.3"
tokio = { version = "1.38.0", features = ["full"] }
